CREATE TABLE IF NOT EXISTS `mb_giros` (
  `GIRO_ID` int(11) NOT NULL,
  `GIRO_TMP_ID` int(11) NOT NULL,
  `GIRO_PRG_ID` int(11) NOT NULL,
  `GIRO_CONDUCTOR_ID` int(11) NOT NULL,
  `GIRO_RECAUDADOR_ID` int(11) NOT NULL,
  `GIRO_SALE` date NOT NULL,
  `GIRO_LLEGA` date NOT NULL,
  `GIRO_REGISTRO` date NOT NULL,
  `GIRO_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `GIRO_USUARIO` varchar(20) NOT NULL,
  `GIRO_ESTADO` varchar(20) NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`GIRO_PRG_ID`, `GIRO_ID`),  
  KEY `GIRO_CONDUCTOR_ID` (`GIRO_CONDUCTOR_ID`),
  KEY `GIRO_RECAUDADOR_ID` (`GIRO_RECAUDADOR_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `mb_herramientas` (
  `HRR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `HRR_TIPO_HERRAMIENTA_ID` int(11) NOT NULL,
  `HRR_DESCRIPCION` varchar(255) NOT NULL,
  `HRR_DETALLE` text NOT NULL,
  `HRR_REGISTRO` date NOT NULL,
  `HRR_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `HRR_USUARIO` varchar(20) NOT NULL,
  `HRR_ESTADO` varchar(20) NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`HRR_ID`),
  KEY `HRR_TIPO_HERRAMIENTA_ID` (`HRR_TIPO_HERRAMIENTA_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `MB_LIQUIDACIONES` (
  `LQD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LQD_ANFITRION` int(11) NOT NULL,
  `LQD_CAJERO` int(11),
  `LQD_HRR_ID` int(11) NOT NULL,
  `LQD_PRG_ID` int(11) NULL,
  `LQD_GIRO_ID` int(11) NULL,
  `LQD_RUTA_ID` int(11) NULL,
  `LQD_MONTO` varchar(20) NULL,
  `LQD_CONFIRMADO` varchar(20) NOT NULL DEFAULT 'NO',
  `LQD_FLUJO` varchar(20) NOT NULL DEFAULT 'INGRESO',
  `LQD_TIPO` varchar(20) NOT NULL DEFAULT 'NINGUNO',
  `LQD_MONTOSF` varchar(20) NOT NULL DEFAULT '0',
  `LQD_REGISTRO` DATETIME NULL,
  `LQD_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LQD_USUARIO` varchar(20) NOT NULL,
  `LQD_ESTADO` varchar(20) NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`LQD_ID`),
  KEY `LQD_ANFITRION` (`LQD_ANFITRION`),
  KEY `LQD_CAJERO` (`LQD_CAJERO`),
  KEY `LQD_HRR_ID` (`LQD_HRR_ID`)  
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
  
CREATE TABLE IF NOT EXISTS `mb_paradas` (
  `PARADA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PARADA_DESCRIPCION` varchar(255) NOT NULL,
  `PARADA_DETALLE` text NOT NULL,
  `PARADA_LONGITUD` varchar(100) NOT NULL DEFAULT '-68.14387903976389',
  `PARADA_LATITUD` varchar(100) NOT NULL DEFAULT '-16.50848616131211',
  `PARADA_ORDEN` int(11) NOT NULL DEFAULT '10',
  `PARADA_REGISTRO` date NOT NULL,
  `PARADA_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `PARADA_USUARIO` varchar(20) NOT NULL,
  `PARADA_ESTADO` varchar(20) NOT NULL DEFAULT 'INACTIVO',
  PRIMARY KEY (`PARADA_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `mb_patios` (
  `PATIO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PATIO_DESCRIPCION` varchar(255) NOT NULL,
  `PATIO_DETALLE` text NOT NULL,
  `PATIO_REGISTRO` date NOT NULL,
  `PATIO_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `PATIO_USUARIO` varchar(20) NOT NULL,
  `PATIO_ESTADO` varchar(20) NOT NULL DEFAULT 'INACTIVO',
  PRIMARY KEY (`PATIO_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
 
CREATE TABLE IF NOT EXISTS `mb_programaciones` (
  `PRG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRG_HRR_ID` int(11) NOT NULL,
  `PRG_CONDUCTOR_ID` int(11) NOT NULL,
  `PRG_RUTA_ID` int(11) NOT NULL,
  `PRG_REGISTRO` date NOT NULL,
  `PRG_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `PRG_USUARIO` varchar(20) NOT NULL,
  `PRG_ESTADO` varchar(20) NOT NULL DEFAULT 'INACTIVO',
  PRIMARY KEY (`PRG_ID`),
  KEY `PRG_HRR_ID` (`PRG_HRR_ID`),
  KEY `PRG_RUTA_ID` (`PRG_RUTA_ID`),
  KEY `PRG_CONDUCTOR_ID` (`PRG_CONDUCTOR_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `mb_rts_prds` (
  `RTS_PRD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RTS_PRD_RUTA_ID` int(11) NOT NULL,
  `RTS_PRD_PARADA_ID` int(11) NOT NULL,
  `RTS_PRD_REGISTRO` date NOT NULL,
  `RTS_PRD_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `RTS_PRD_USUARIO` varchar(20) NOT NULL,
  `RTS_PRD_ESTADO` varchar(20) NOT NULL DEFAULT 'INACTIVO',
  PRIMARY KEY (`RTS_PRD_ID`),
  KEY `RTS_PRD_RUTA_ID` (`RTS_PRD_RUTA_ID`),
  KEY `RTS_PRD_PARADA_ID` (`RTS_PRD_PARADA_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `mb_rts_ptis` (
  `RTS_PTI_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RTS_PTI_RUTA_ID` int(11) NOT NULL,
  `RTS_PTI_PATIO_ID` int(11) NOT NULL,
  `RTS_PTI_REGISTRO` date NOT NULL,
  `RTS_PTI_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `RTS_PTI_USUARIO` varchar(20) NOT NULL,
  `RTS_PTI_ESTADO` varchar(20) NOT NULL DEFAULT 'INACTIVO',
  PRIMARY KEY (`RTS_PTI_ID`),
  KEY `RTS_PTI_RUTA_ID` (`RTS_PTI_RUTA_ID`),
  KEY `RTS_PTI_PATIO_ID` (`RTS_PTI_PATIO_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `mb_rutas` (
  `RUTA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RUTA_DESCRIPCION` varchar(255) NOT NULL,
  `RUTA_DETALLE` text NOT NULL,
  `RUTA_REGISTRO` date NOT NULL,
  `RUTA_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `RUTA_USUARIO` varchar(20) NOT NULL,
  `RUTA_ESTADO` varchar(20) NOT NULL DEFAULT 'INACTIVO',
  PRIMARY KEY (`RUTA_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `mb_tarifas` (
  `TARIFA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TARIFA_TIPO_PASAJE_ID` int(11) NOT NULL,
  `TARIFA_DESCRIPCION` varchar(255) NOT NULL,
  `TARIFA_NRO_RESOLUCION` varchar(255) NOT NULL,
  `TARIFA_MONTO` decimal(12,2) NOT NULL DEFAULT '0.00',
  `TARIFA_REGISTRO` date NOT NULL,
  `TARIFA_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TARIFA_USUARIO` varchar(20) NOT NULL,
  `TARIFA_ESTADO` varchar(20) NOT NULL DEFAULT 'INACTIVO',
  PRIMARY KEY (`TARIFA_ID`),
  KEY `TARIFA_TIPO_PASAJE_ID` (`TARIFA_TIPO_PASAJE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `mb_tipos_funcionario` (
  `TIPO_FUNCIONARIO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO_FUNCIONARIO_DESCRIPCION` varchar(50) NOT NULL,
  `TIPO_FUNCIONARIO_REGISTRO` date NOT NULL,
  `TIPO_FUNCIONARIO_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TIPO_FUNCIONARIO_USUARIO` varchar(20) NOT NULL,
  `TIPO_FUNCIONARIO_ESTADO` varchar(20) NOT NULL DEFAULT 'INACTIVO',
  PRIMARY KEY (`TIPO_FUNCIONARIO_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `mb_tipos_herramienta` (
  `TIPO_HERRAMIENTA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO_HERRAMIENTA_CODIGO` varchar(20) NOT NULL,
  `TIPO_HERRAMIENTA_DESCRIPCION` text NOT NULL,
  `TIPO_HERRAMIENTA_ASIENTOS` int(11) NOT NULL,
  `TIPO_HERRAMIENTA_REGISTRO` date NOT NULL,
  `TIPO_HERRAMIENTA_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TIPO_HERRAMIENTA_USUARIO` varchar(20) NOT NULL,
  `TIPO_HERRAMIENTA_ESTADO` varchar(20) NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`TIPO_HERRAMIENTA_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `mb_tipos_pasaje` (
  `TIPO_PASAJE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO_PASAJE_CODIGO` varchar(20) NOT NULL,
  `TIPO_PASAJE_DESCRIPCION` varchar(255) NOT NULL,
  `TIPO_PASAJE_REGISTRO` date NOT NULL,
  `TIPO_PASAJE_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TIPO_PASAJE_USUARIO` varchar(20) NOT NULL,
  `TIPO_PASAJE_ESTADO` varchar(20) NOT NULL DEFAULT 'INACTIVO',
  PRIMARY KEY (`TIPO_PASAJE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `mb_trxs` (
  `TRX_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRX_PRG_ID` int(11)  NULL,
   TRX_LQD_ID  int(11) NULL,
  `TRX_HERRAMIENTA_ID` int(11)  NULL,
  `TRX_PARADA_ID` varchar(20)  NULL,
  `TRX_TARIFA` varchar(50) NULL,
  `TRX_GIRO_ID` int(11)  NULL,
  `TRX_TIPO_PASAJE_ID` int(11)  NULL,
  `TRX_NRO_TARJETA` varchar(20)  NULL,
  `TRX_NRO_FACTURA` varchar(20)  NULL,

  `TRX_RUTA_ID` INT(11)  NULL,
  `TRX_TIPO_HERRAMIENTA_ID` INT(11) NULL,

  `TRX_REGISTRO` DATETIME NOT NULL,
  `TRX_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TRX_USUARIO` varchar(20) NOT NULL DEFAULT 'ADMIN',
  `TRX_ESTADO` varchar(20) NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`TRX_ID`),
  KEY `TRX_GIRO_ID` (`TRX_GIRO_ID`),
  KEY `TRX_TIPO_PASAJE_ID` (`TRX_TIPO_PASAJE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `sa_estados_civiles` (
  `ESTADO_CIVIL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ESTADO_CIVIL_DESCRIPCION` varchar(255) NOT NULL,
  `ESTADO_CIVIL_REGISTRADO` datetime NOT NULL,
  `ESTADO_CIVIL_MODIFICADO` datetime NOT NULL,
  `ESTADO_CIVIL_USUARIO` varchar(20) NOT NULL,
  `ESTADO_CIVIL_ESTADO` char(1) NOT NULL,
  PRIMARY KEY (`ESTADO_CIVIL_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `sa_expedidos` (
  `EXPEDIDO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EXPEDIDO_CODIGO` varchar(255) NOT NULL,
  `EXPEDIDO_DESCRIPCION` varchar(255) NOT NULL,
  `EXPEDIDO_REGISTRADO` datetime NOT NULL,
  `EXPEDIDO_MODIFICADO` datetime NOT NULL,
  `EXPEDIDO_USUARIO` varchar(20) NOT NULL,
  `EXPEDIDO_ESTADO` char(1) NOT NULL,
  PRIMARY KEY (`EXPEDIDO_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `sa_grupos` (
  `GRUPO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GRUPO_DESCRIPCION` varchar(255) NOT NULL,
  `GRUPO_IMAGEN` varchar(255) NOT NULL,
  `GRUPO_REGISTRADO` datetime NOT NULL,
  `GRUPO_MODIFICADO` datetime NOT NULL,
  `GRUPO_USUARIO` varchar(20) NOT NULL,
  `GRUPO_ESTADO` char(1) NOT NULL,
  PRIMARY KEY (`GRUPO_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `sa_opciones` (
  `OPCION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `OPCION_GRUPO_ID` int(11) NOT NULL,
  `OPCION_DESCRIPCION` varchar(255) NOT NULL,
  `OPCION_CONTENIDO` varchar(255) NOT NULL,
  `OPCION_ADICIONAL` varchar(255) NOT NULL,
  `OPCION_ORDEN` int(11) NOT NULL,
  `OPCION_IMAGEN` varchar(255) NOT NULL,
  `OPCION_REGISTRADO` datetime NOT NULL,
  `OPCION_MODIFICADO` datetime NOT NULL,
  `OPCION_USUARIO` varchar(20) NOT NULL,
  `OPCION_ESTADO` char(1) NOT NULL,
  PRIMARY KEY (`OPCION_ID`),
  KEY `OPCION_GRUPO_ID` (`OPCION_GRUPO_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `sa_accesos` (
  `ACCESO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCESO_OPCION_ID` int(11) NOT NULL,
  `ACCESO_TIPO_FUNCIONARIO_ID` int(11) NOT NULL,
  `ACCESO_REGISTRADO` datetime NOT NULL,
  `ACCESO_MODIFICADO` datetime NOT NULL,
  `ACCESO_USUARIO` varchar(20) NOT NULL,
  `ACCESO_ESTADO` char(1) NOT NULL,
  PRIMARY KEY (`ACCESO_ID`),
  KEY `ACCESO_OPCION_ID` (`ACCESO_OPCION_ID`),
  KEY `ACCESO_TIPO_FUNCIONARIO_ID` (`ACCESO_TIPO_FUNCIONARIO_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `mb_funcionarios` (
  `FUNCIONARIO_ID` int(11) NOT NULL AUTO_INCREMENT,  
  `FUNCIONARIO_EXPEDIDO_ID` int(11) NOT NULL,
  `FUNCIONARIO_ESTADO_CIVIL_ID` int(11) NOT NULL,  
  `FUNCIONARIO_CI` varchar(45) NOT NULL,
  `FUNCIONARIO_NOMBRES` varchar(50) NOT NULL,
  `FUNCIONARIO_PATERNO` varchar(45) DEFAULT NULL,
  `FUNCIONARIO_MATERNO` varchar(45) NOT NULL,
  `FUNCIONARIO_REGISTRO` date NOT NULL,
  `FUNCIONARIO_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FUNCIONARIO_USUARIO` varchar(20) NOT NULL,
  `FUNCIONARIO_ESTADO` varchar(20) NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`FUNCIONARIO_ID`),  
  KEY `FUNCIONARIO_EXPEDIDO_ID` (`FUNCIONARIO_EXPEDIDO_ID`),
  KEY `FUNCIONARIO_ESTADO_CIVIL_ID` (`FUNCIONARIO_ESTADO_CIVIL_ID`)  
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `sa_usuarios` (
  `USUARIO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USUARIO_FUNCIONARIO_ID` int(11) NOT NULL,
  `USUARIO_CODIGO` varchar(255) NOT NULL,
  `USUARIO_CLAVE` varchar(255) NOT NULL,
  `USUARIO_CONTROLAR_IP` char(1) NOT NULL,
  `USUARIO_REGISTRADO` datetime NOT NULL,
  `USUARIO_MODIFICADO` datetime NOT NULL,
  `USUARIO_USUARIO` varchar(20) NOT NULL,
  `USUARIO_ESTADO` char(1) NOT NULL,
  `USUARIO_CORREO` varchar(255) NOT NULL,
  `USUARIO_TIPO_USUARIO` char(1) NOT NULL,
  `USUARIO_DOMINIO` char(1) NOT NULL,
  PRIMARY KEY (`USUARIO_ID`),
  KEY `USUARIO_FUNCIONARIO_ID` (`USUARIO_FUNCIONARIO_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS `sa_usuario_tipos_funcionario` (
  `UTF_ID` int(11) NOT NULL AUTO_INCREMENT,
  `UTF_USUARIO_ID` int(11) NOT NULL,
  `UTF_TIPO_FUNCIONARIO_ID` int(11) NOT NULL,
  `UTF_REGISTRADO` datetime NOT NULL,
  `UTF_MODIFICADO` datetime NOT NULL,
  `UTF_USUARIO` varchar(20) NOT NULL,
  `UTF_ESTADO` char(1) NOT NULL,
  PRIMARY KEY (`UTF_ID`),
  KEY `UTF_USUARIO_ID` (`UTF_USUARIO_ID`),
  KEY `UTF_TIPO_FUNCIONARIO_ID` (`UTF_TIPO_FUNCIONARIO_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `mb_liq_manuales` (
  `LQD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LQD_ANFITRION` int(11) NOT NULL,
  `LQD_CAJERO` int(11),
  `LQD_HRR_ID` int(11) NOT NULL,
  `LQD_PRG_ID` int(11) NULL,
  `LQD_RUTA_ID` int(11) NULL,
  `LQD_TIPO_HERRAMIENTA_ID` int(11) NULL,
  `LQD_GIRO_ID` int(11) NULL,  
  `LQD_MONTO` varchar(20) NULL,
  `LQD_CONFIRMADO` varchar(20) NOT NULL DEFAULT 'NO',
  `LQD_FLUJO` varchar(20) NOT NULL DEFAULT 'INGRESO',
  `LQD_TIPO` varchar(20) NOT NULL DEFAULT 'NINGUNO',
  `LQD_MONTOSF` varchar(20) NOT NULL DEFAULT '0',
  `LQD_ND` int(11) NOT NULL DEFAULT '0',
  `LQD_NN` int(11) NOT NULL DEFAULT '0',
  `LQD_PD` int(11) NOT NULL DEFAULT '0',
  `LQD_PN` int(11) NOT NULL DEFAULT '0',
  `LQD_NRO_MAGICO` varchar(50) NOT NULL ,  
  `LQD_REGISTRO` DATETIME NULL,
  `LQD_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LQD_USUARIO` varchar(20) NOT NULL,
  `LQD_ESTADO` varchar(20) NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`LQD_ID`),
  KEY `LQD_ANFITRION` (`LQD_ANFITRION`),
  KEY `LQD_CAJERO` (`LQD_CAJERO`),
  KEY `LQD_HRR_ID` (`LQD_HRR_ID`)  
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

  
CREATE TABLE IF NOT EXISTS `mb_liq_automaticas` (
  `LQD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LQD_ANFITRION` int(11) NOT NULL,
  `LQD_CAJERO` int(11),
  `LQD_HRR_ID` int(11)  NULL,
  `LQD_TIPO_HERRAMIENTA_ID` int(11) NULL,
  `LQD_PRG_ID` int(11) NULL,
  `LQD_RUTA_ID` int(11) NULL,
  `LQD_GIRO_ID` int(11) NULL,
  `LQD_MONTO` varchar(20) NULL,
  `LQD_CONFIRMADO` varchar(20) NOT NULL DEFAULT 'NO',
  `LQD_FLUJO` varchar(20) NOT NULL DEFAULT 'INGRESO',
  `LQD_TIPO` varchar(20) NOT NULL DEFAULT 'NINGUNO',
  `LQD_MONTOSF` varchar(20) NOT NULL DEFAULT '0',
  `LQD_ND` int(11) NOT NULL DEFAULT '0',
  `LQD_NN` int(11) NOT NULL DEFAULT '0',
  `LQD_PD` int(11) NOT NULL DEFAULT '0',
  `LQD_PN` int(11) NOT NULL DEFAULT '0',
  `LQD_NRO_MAGICO` varchar(50) NOT NULL ,  
  `LQD_REGISTRO` DATETIME NULL,
  `LQD_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LQD_USUARIO` varchar(20) NOT NULL,
  `LQD_ESTADO` varchar(20) NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`LQD_ID`),
  KEY `LQD_ANFITRION` (`LQD_ANFITRION`),
  KEY `LQD_CAJERO` (`LQD_CAJERO`),
  KEY `LQD_HRR_ID` (`LQD_HRR_ID`)  
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


ALTER TABLE `mb_funcionarios`
  ADD CONSTRAINT `MB_FUNCIONARIOS_ibfk_1` FOREIGN KEY (`FUNCIONARIO_EXPEDIDO_ID`) REFERENCES `sa_expedidos` (`EXPEDIDO_ID`),
  ADD CONSTRAINT `MB_FUNCIONARIOS_ibfk_2` FOREIGN KEY (`FUNCIONARIO_ESTADO_CIVIL_ID`) REFERENCES `sa_estados_civiles` (`ESTADO_CIVIL_ID`);
  

ALTER TABLE `mb_giros`
  ADD CONSTRAINT `MB_GIROS_ibfk_2` FOREIGN KEY (`GIRO_CONDUCTOR_ID`) REFERENCES `mb_funcionarios` (`FUNCIONARIO_ID`),
  ADD CONSTRAINT `MB_GIROS_ibfk_3` FOREIGN KEY (`GIRO_RECAUDADOR_ID`) REFERENCES `mb_funcionarios` (`FUNCIONARIO_ID`);


ALTER TABLE `mb_herramientas`
  ADD CONSTRAINT `MB_HERRAMIENTAS_ibfk_1` FOREIGN KEY (`HRR_TIPO_HERRAMIENTA_ID`) REFERENCES `mb_tipos_herramienta` (`TIPO_HERRAMIENTA_ID`);

ALTER TABLE `mb_programaciones`
  ADD CONSTRAINT `MB_PROGRAMACIONES_ibfk_1` FOREIGN KEY (`PRG_HRR_ID`) REFERENCES `mb_herramientas` (`HRR_ID`),
  ADD CONSTRAINT `MB_PROGRAMACIONES_ibfk_3` FOREIGN KEY (`PRG_RUTA_ID`) REFERENCES `mb_rutas` (`RUTA_ID`),
  ADD CONSTRAINT `MB_PROGRAMACIONES_ibfk_4` FOREIGN KEY (`PRG_CONDUCTOR_ID`) REFERENCES `mb_funcionarios` (`FUNCIONARIO_ID`);

ALTER TABLE `mb_rts_prds`
  ADD CONSTRAINT `MB_RTS_PRDS_ibfk_1` FOREIGN KEY (`RTS_PRD_RUTA_ID`) REFERENCES `mb_rutas` (`RUTA_ID`),
  ADD CONSTRAINT `MB_RTS_PRDS_ibfk_2` FOREIGN KEY (`RTS_PRD_PARADA_ID`) REFERENCES `mb_paradas` (`PARADA_ID`);

ALTER TABLE `mb_rts_ptis`
  ADD CONSTRAINT `MB_RTS_PTIS_ibfk_1` FOREIGN KEY (`RTS_PTI_RUTA_ID`) REFERENCES `mb_rutas` (`RUTA_ID`),
  ADD CONSTRAINT `MB_RTS_PTIS_ibfk_2` FOREIGN KEY (`RTS_PTI_PATIO_ID`) REFERENCES `mb_patios` (`PATIO_ID`);

ALTER TABLE `mb_tarifas`
  ADD CONSTRAINT `MB_TARIFAS_ibfk_1` FOREIGN KEY (`TARIFA_TIPO_PASAJE_ID`) REFERENCES `mb_tipos_pasaje` (`TIPO_PASAJE_ID`);

ALTER TABLE `mb_trxs`
  ADD CONSTRAINT `MB_TRXS_ibfk_2` FOREIGN KEY (`TRX_TIPO_PASAJE_ID`) REFERENCES `mb_tipos_pasaje` (`TIPO_PASAJE_ID`);


ALTER TABLE `sa_accesos`
  ADD CONSTRAINT `sa_accesos_ibfk_1` FOREIGN KEY (`ACCESO_OPCION_ID`) REFERENCES `sa_opciones` (`OPCION_ID`),
  ADD CONSTRAINT `sa_accesos_ibfk_2` FOREIGN KEY (`ACCESO_TIPO_FUNCIONARIO_ID`) REFERENCES `mb_tipos_funcionario` (`TIPO_FUNCIONARIO_ID`);

ALTER TABLE `sa_opciones`
  ADD CONSTRAINT `sa_opciones_ibfk_1` FOREIGN KEY (`OPCION_GRUPO_ID`) REFERENCES `sa_grupos` (`GRUPO_ID`);

ALTER TABLE `sa_usuarios`
  ADD CONSTRAINT `sa_usuarios_ibfk_1` FOREIGN KEY (`USUARIO_FUNCIONARIO_ID`) REFERENCES `mb_funcionarios` (`FUNCIONARIO_ID`);

ALTER TABLE `sa_usuario_tipos_funcionario`
  ADD CONSTRAINT `sa_usuario_tipos_funcionario_ibfk_1` FOREIGN KEY (`UTF_USUARIO_ID`) REFERENCES `sa_usuarios` (`USUARIO_ID`),
  ADD CONSTRAINT `sa_usuario_tipos_funcionario_ibfk_2` FOREIGN KEY (`UTF_TIPO_FUNCIONARIO_ID`) REFERENCES `mb_tipos_funcionario` (`TIPO_FUNCIONARIO_ID`);

ALTER TABLE `MB_LIQUIDACIONES`
  ADD CONSTRAINT `MB_LIQUIDACIONES_ibfk_1` FOREIGN KEY (`LQD_ANFITRION`) REFERENCES `MB_FUNCIONARIOS` (`FUNCIONARIO_ID`),
  ADD CONSTRAINT `MB_LIQUIDACIONES_ibfk_2` FOREIGN KEY (`LQD_CAJERO`) REFERENCES `MB_FUNCIONARIOS` (`FUNCIONARIO_ID`),
  ADD CONSTRAINT `MB_LIQUIDACIONES_ibfk_3` FOREIGN KEY (`LQD_HRR_ID`) REFERENCES `MB_HERRAMIENTAS` (`HRR_ID`);