-- EJECUTAR EN LA BASE-DATOS DEL SERVIDOR PARA LA SINCRONIZACION
-- OFICIAL EN EL 82
DELIMITER $$
CREATE PROCEDURE spObtenerLiquidacionHerramienta(
IN HERRAMIENTA_ID INT,
IN LQD_ID_LOCAL_MAXIMO INT)
BEGIN
SELECT LQD_ID, LQD_ANFITRION, LQD_CAJERO, LQD_HRR_ID, LQD_PRG_ID, LQD_GIRO_ID, LQD_MONTO, LQD_CONFIRMADO, LQD_FLUJO, LQD_REGISTRO, LQD_MODIFICACION, LQD_USUARIO, LQD_ESTADO 
FROM mb_liquidaciones
WHERE LQD_HRR_ID = HERRAMIENTA_ID AND LQD_ID > LQD_ID_LOCAL_MAXIMO AND LQD_ESTADO = 'ACTIVO';
END$$
DELIMITER ; 

-- CALL spObtenerLiquidacionHerramienta(1,1);



