<?php
require('dbVersion02.php');
LocalInstanciarConexion();

try {
    $option = $_REQUEST["option"];
    switch ($option) {
        case "LST": $pageSize = $_REQUEST["pageSize"];                  
                    $limit = isset($_REQUEST["limit"])? $_REQUEST["limit"] : $pageSize;
                    $start = isset($_REQUEST["start"])? $_REQUEST["start"] : 0;
					$consultaSql = "(SELECT PROGRAMACION_IT_ID, RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_LUNES) AS PROGRAMACION_IT_FECHA_LUNES, PROGRAMACION_IT_LUNES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_LUNES<>'0000-00-00 00:00:00')
									UNION
									(SELECT PROGRAMACION_IT_ID, RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_MARTES), PROGRAMACION_IT_MARTES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_MARTES<>'0000-00-00 00:00:00')
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_MIERCOLES), PROGRAMACION_IT_MIERCOLES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_MIERCOLES<>'0000-00-00 00:00:00' )
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_JUEVES), PROGRAMACION_IT_JUEVES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_JUEVES<>'0000-00-00 00:00:00' )
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_VIERNES), PROGRAMACION_IT_VIERNES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_VIERNES<>'0000-00-00 00:00:00' )
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_SABADO), PROGRAMACION_IT_SABADO
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_SABADO<>'0000-00-00 00:00:00' )
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_DOMINGO), PROGRAMACION_IT_DOMINGO
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_DOMINGO<>'0000-00-00 00:00:00')";
									
					$respuesta=LocalExecuteQuery($consultaSql);
					doGenerarJsonRespuesta($respuesta,$start,$limit);
                    break;

        case "LST_RUTA": 
        			$ruta = $_REQUEST["vRuta"];
        			$pageSize = $_REQUEST["pageSize"]; 
                    $limit = isset($_REQUEST["limit"])? $_REQUEST["limit"] : $pageSize;
                    $start = isset($_REQUEST["start"])? $_REQUEST["start"] : 0;
                  
					$consultaSql = "(SELECT PROGRAMACION_IT_ID, RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_LUNES) AS PROGRAMACION_IT_FECHA_LUNES, PROGRAMACION_IT_LUNES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_LUNES<>'0000-00-00 00:00:00' AND PROGRAMACION_IT_RUTA_ID='$ruta')
									UNION
									(SELECT PROGRAMACION_IT_ID, RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_MARTES), PROGRAMACION_IT_MARTES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_MARTES<>'0000-00-00 00:00:00' AND PROGRAMACION_IT_RUTA_ID='$ruta')
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_MIERCOLES), PROGRAMACION_IT_MIERCOLES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_MIERCOLES<>'0000-00-00 00:00:00' AND PROGRAMACION_IT_RUTA_ID='$ruta')
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_JUEVES), PROGRAMACION_IT_JUEVES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_JUEVES<>'0000-00-00 00:00:00' AND PROGRAMACION_IT_RUTA_ID='$ruta')
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_VIERNES), PROGRAMACION_IT_VIERNES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_VIERNES<>'0000-00-00 00:00:00' AND PROGRAMACION_IT_RUTA_ID='$ruta')
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_SABADO), PROGRAMACION_IT_SABADO
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_SABADO<>'0000-00-00 00:00:00' AND PROGRAMACION_IT_RUTA_ID='$ruta')
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_DOMINGO), PROGRAMACION_IT_DOMINGO
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  PROGRAMACION_IT_FECHA_DOMINGO<>'0000-00-00 00:00:00' AND PROGRAMACION_IT_RUTA_ID='$ruta')";
									//echo($consultaSql);
                    $respuesta=LocalExecuteQuery($consultaSql);
					doGenerarJsonRespuesta($respuesta,$start,$limit);
                    break;

        case "LST_TURNOS": 
					//$sHospital_id = $_REQUEST["jsGlobal_TF_HSP_ID"];
					$consultaSql = "SELECT RUTA_ID,RUTA_DESCRIPCION,RUTA_DETALLE,RUTA_ESTADO FROM MB_RUTAS WHERE RUTA_ESTADO='ACTIVO'";

					$respuesta=LocalExecuteQuery($consultaSql);
					doGenerarJsonRespuesta($respuesta,0,1000);
					break;

        case "BUSQUEDA": 
        			$ruta = $_REQUEST["vRuta"];
        			$fecha = $_REQUEST["vFecha"];
        			$fecha2 = $_REQUEST["vFechaF"];
        			$pageSize = $_REQUEST["pageSize"]; 
                    $limit = isset($_REQUEST["limit"])? $_REQUEST["limit"] : $pageSize;
                    $start = isset($_REQUEST["start"])? $_REQUEST["start"] : 0;
                    if($ruta=="")
                    {	
						$consultaSql = "(SELECT PROGRAMACION_IT_ID, RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_LUNES) AS PROGRAMACION_IT_FECHA_LUNES, PROGRAMACION_IT_LUNES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND (DATE(PROGRAMACION_IT_FECHA_LUNES) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID, RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_MARTES), PROGRAMACION_IT_MARTES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  (DATE(PROGRAMACION_IT_FECHA_MARTES) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_MIERCOLES), PROGRAMACION_IT_MIERCOLES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  (DATE(PROGRAMACION_IT_FECHA_MIERCOLES) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_JUEVES), PROGRAMACION_IT_JUEVES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  (DATE(PROGRAMACION_IT_FECHA_JUEVES) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_VIERNES), PROGRAMACION_IT_VIERNES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  (DATE(PROGRAMACION_IT_FECHA_VIERNES) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_SABADO), PROGRAMACION_IT_SABADO
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  (DATE(PROGRAMACION_IT_FECHA_SABADO) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_DOMINGO), PROGRAMACION_IT_DOMINGO
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND  (DATE(PROGRAMACION_IT_FECHA_DOMINGO) BETWEEN '$fecha' AND '$fecha2'))";
					}
					else{
						$consultaSql = "(SELECT PROGRAMACION_IT_ID, RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_LUNES) AS PROGRAMACION_IT_FECHA_LUNES, PROGRAMACION_IT_LUNES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND PROGRAMACION_IT_RUTA_ID='$ruta' AND (DATE(PROGRAMACION_IT_FECHA_LUNES) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID, RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_MARTES), PROGRAMACION_IT_MARTES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND PROGRAMACION_IT_RUTA_ID='$ruta' AND  (DATE(PROGRAMACION_IT_FECHA_MARTES) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_MIERCOLES), PROGRAMACION_IT_MIERCOLES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND PROGRAMACION_IT_RUTA_ID='$ruta' AND  (DATE(PROGRAMACION_IT_FECHA_MIERCOLES) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_JUEVES), PROGRAMACION_IT_JUEVES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND PROGRAMACION_IT_RUTA_ID='$ruta' AND  (DATE(PROGRAMACION_IT_FECHA_JUEVES) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_VIERNES), PROGRAMACION_IT_VIERNES
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND PROGRAMACION_IT_RUTA_ID='$ruta' AND  (DATE(PROGRAMACION_IT_FECHA_VIERNES) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_SABADO), PROGRAMACION_IT_SABADO
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND PROGRAMACION_IT_RUTA_ID='$ruta' AND  (DATE(PROGRAMACION_IT_FECHA_SABADO) BETWEEN '$fecha' AND '$fecha2'))
									UNION
									(SELECT PROGRAMACION_IT_ID,RUTA_DESCRIPCION, TIPO_HERRAMIENTA_CODIGO, DATE(PROGRAMACION_IT_FECHA_DOMINGO), PROGRAMACION_IT_DOMINGO
									FROM mb_programacion_itinerarios
									INNER JOIN mb_rutas ON PROGRAMACION_IT_RUTA_ID = RUTA_ID
									INNER JOIN mb_tipos_herramienta ON PROGRAMACION_IT_TIPO_HERRAMIENTA_ID = TIPO_HERRAMIENTA_ID
									where PROGRAMACION_IT_ESTADO = 'ACTIVO' AND PROGRAMACION_IT_RUTA_ID='$ruta' AND  (DATE(PROGRAMACION_IT_FECHA_DOMINGO) BETWEEN '$fecha' AND '$fecha2'))";
					}
                    $respuesta=LocalExecuteQuery($consultaSql);
					doGenerarJsonRespuesta($respuesta,$start,$limit);
                    break;
    }
} catch (Exception $e) {
    echo null;
}
LocalCerrarConexion();
?>